internalName: crk_keyboard

locales:
  en:
    name: &bundleName "Plains Cree Keyboards"
    description: "Mobile OS keyboards for  languages from the Divvun group at UiT."
  crk:
    name: "nēhiyawēwin"
    description: "Mobiltastatur for fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2016 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [crk]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.
    icon: sami-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.
    bundleName: *bundleName
    icon:
        90: sami-icon-small.png
        150: sami-icon.png
  osx: *AppleID
